# fichier test

In [1]:
import numpy as np

In [3]:
t = np.ones((10,5))
t[:]

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
t = np.ones((10,5))
t[:] = 0
t

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
t = np.ones((10,5))
t[::] = 0
t

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
t = np.ones((10,5))
t[::,::] = 0
t

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
t = np.ones((10,5))
t = 0
t

0

In [19]:
b = np.array([[2,2,2],
              [3,5,6],
              [8,0,4]])

np.sum(b,axis=0) # on somme les tableaux de 3

array([13,  7, 12])

In [21]:
np.sum(b,axis=1)

array([ 6, 14, 12])

# explication de l'addition broadcast de tableaux numpy

In [29]:
a = np.random.randint(0,10,(2,3))
b = np.random.randint(0,10,(2,1))
c = np.random.randint(0,10,(1,3))

In [28]:
print(a,b,a+b,sep="\n")

[[0 4 6]
 [7 7 3]]
[[8]
 [5]]
[[ 8 12 14]
 [12 12  8]]


In [31]:
print(a,c,a+c,sep="\n")

[[0 8 5]
 [7 4 3]]
[[7 5 2]]
[[ 7 13  7]
 [14  9  5]]


In [35]:
(a > 2).shape

(2, 3)